### ISSUE TITLE
Make an option for restaurant to register

### ISSUE THREAD

**Issue by KripashStha** [OneByte-Foods/ONE-BYTE-FOOD-WEB#10]
There will be two actors restaurant and users, if logined as restaurant then give them all the access and if user then the admin can decide the role for the user and based on the role they will get certain permissions.

![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/128284556/50acdba3-1d80-4088-9df1-89c3311a6269)

**Comment by Bikalpa-Paudel** [comment]
![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/89839823/4287d39e-eff6-41a4-a54f-0a3e47635fa4)

I have made a separate form for restaurants  to register
