### ISSUE TITLE
Links are not working in contacts section

### ISSUE THREAD

**Issue by KripashStha** [OneByte-Foods/ONE-BYTE-FOOD-WEB#13]
The facebook and instagram social links are not working in the home page.

![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/128284556/728e852a-34f9-4b7b-b4cc-1d681cae3b98)

**Comment by Bikalpa-Paudel** [comment]
![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/89839823/6ed8a5bd-7f00-4bb0-8707-c0d43be36560)

now it should be working fine
