### ISSUE TITLE
Colour the Dashboard

### ISSUE THREAD

**Issue by UnikRai** [OneByte-Foods/ONE-BYTE-FOOD-WEB#14]
The dashboard is currently black and white but we can play with some colors.
![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/128683169/3d93ef4b-ede5-4956-9e23-b0c5369fc1b5)

**Comment by Rrasikbohara** [comment]
![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/162891567/cc97fdf4-4802-4efa-bfb9-7672e6fd317b)
