### ISSUE TITLE
Redesign Dashboard of admin panel

### ISSUE THREAD

**Issue by KripashStha** [OneByte-Foods/ONE-BYTE-FOOD-WEB#19]

**Comment by Bikalpa-Paudel** [comment]
![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/89839823/e78cfd3c-0dbe-48a9-b422-9302a9f3c3fa)
![image](https://github.com/OneByte-Foods/ONE-BYTE-FOOD-WEB/assets/89839823/03ba1af3-cd7b-4993-8d35-246654c7037b)

I all the section of admin dashboard
